# Generated by Django 5.0.1 on 2024-01-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_book_book_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="MindSpace_Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_query", models.TextField(max_length=30000)),
            ],
        ),
    ]
